# Generated by Django 4.0.6 on 2022-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(db_index=True, max_length=50, verbose_name='Наименование МЦ')),
            ],
        ),
    ]
