# Generated by Django 4.0.6 on 2022-12-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_material_alter_location_options_alter_location_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['inv_number'], 'verbose_name': 'Матценность', 'verbose_name_plural': 'Матценности'},
        ),
    ]
