# Generated by Django 4.0.6 on 2022-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пункт погрузки/выгрузки',
                'verbose_name_plural': 'Пункты погрузки/выгрузки',
                'ordering': ['name'],
            },
        ),
    ]
