# Generated by Django 4.0.6 on 2022-07-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Расстояние')),
                ('point_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointFinal', to='transport.point', verbose_name='Пункт разгрузки')),
                ('point_start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointStart', to='transport.point', verbose_name='Пункт загрузки')),
            ],
            options={
                'verbose_name': 'Расстояние между складами',
                'verbose_name_plural': 'Расстояние между складами',
                'ordering': ['point_start', 'point_final'],
            },
        ),
    ]
